import RootHeader from "../components/RootHeader";
import RootFooter from "../components/RootFooter";
import NavBar from "../components/NavBar";
import ThemeToggleButton from "@/components/ThemeToggleButton";
import { ThemeProvider } from "@/contexts/ThemeContext";
import CounterProvider from "@/store/CounterProvider";
import Counter from "@/features/counter/Counter";
import "./globals.css";

export const metadata = {
  title: "Next.js Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <CounterProvider>
        <ThemeProvider>
          <body>
            <RootHeader />
            <ThemeToggleButton />
            <Counter />
            <NavBar />
            <main>{children}</main>
            <RootFooter />
          </body>
        </ThemeProvider>
      </CounterProvider>
    </html>
  );
}
