import RootHeader from "../components/RootHeader";
import RootFooter from "../components/RootFooter";
import NavBar from "../components/NavBar";
import ThemeToggleButton from "@/components/ThemeToggleButton";
import { ThemeProvider } from "@/contexts/ThemeContext";
import './globals.css';

export const metadata = {
  title: "Next.js Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <ThemeProvider>
        <body>
          <RootHeader />
          <ThemeToggleButton />
          <NavBar />
          <main>{children}</main>
          <RootFooter />
        </body>
      </ThemeProvider>
    </html>
  );
}
